//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentasMvc.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.FacturasDetalles = new HashSet<FacturaDetalle>();
        }
    
        public int Id { get; set; }
        public int ClienteId { get; set; }
        public decimal MontoNeto { get; set; }
        public decimal MontoImpuesto { get; set; }
        public decimal MontoDescuento { get; set; }
        public decimal MontoTotal { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacturaDetalle> FacturasDetalles { get; set; }
    }
}
